In [ ]:
# Bài 1
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
print("Tổng a và b là: ", a + b)
print("Hiệu a và b là: ", a - b)
print("Tích a và b là: ", a * b)
print("Thương a và b là: ", a / b if b != 0 else print("Không thể chia cho 0"))

Nhập a: 10
Nhập b: 3.5
Tổng a và b là:  13.5
Hiệu a và b là:  6.5
Tích a và b là:  35.0
Thương a và b là:  2.857142857142857


In [ ]:
# Bài 2
s = "Hello World"
print(s[2:5])

llo


In [ ]:
# Bài 3
s2 = "Hello World"
print("Xóa Khoảng Trắng: ", s2.strip())
print("Chuyển sang in hoa: ", s2.upper())
print("Chuyển sang in thường: ", s2.lower())
print("Thay H thành J:", s2.replace('H', 'J'))

Xóa Khoảng Trắng:  Hello World
Chuyển sang in hoa:  HELLO WORLD
Chuyển sang in thường:  hello world
Thay H thành J: Jello World


In [ ]:
# Bài 4
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
if a > b:
    print("Hello World!")
else: print(a, "nhỏ hơn", b)

Nhập a: 6
Nhập b: 7
6.0 nhỏ hơn 7.0


In [ ]:
# Bài 5
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
print("Yes" if a == b else "No")

In [ ]:
# Bài 6
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
print(1 if a == b else 2 if a > b else 3)

In [ ]:
# Bài 7
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
d = float(input("Nhập d: "))
if a == b and b == d:
    print("Hello World!")

In [ ]:
# Bài 8
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
c = float(input("Nhập c: "))
d = float(input("Nhập d: "))
if a == b or c == d:
    print("Hello World!")

In [ ]:
# Bài 9
print("Yes") if a > b else print("No")

In [ ]:
# Bài 10
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
print("A") if a > b else print("=") if a == b else print("B")

In [23]:
# Bài 11
n = int(input("Nhập n: "))
a = []
for i in range(n):
  val = int(input("Nhập giá trị: "))
  a.append(val)
b = [x for x in a if x % 2 == 0]
print(f"Mảng a: {a}")
print(f"Mảng b(số chẵn): {b}")

Nhập n: 3
Nhập giá trị: 4
Nhập giá trị: 5
Nhập giá trị: 6
Mảng a: [4, 5, 6]
Mảng b(số chẵn): [4, 6]


In [27]:

# Bài 12
Dieukien = [x for x in range(1000) if x % 3 == 0 or x % 5 == 0]
print("Các số là bội của 3 và 5: ", Dieukien)
Tong = sum(Dieukien)
print(f"Tổng các số là bội của 3 và 5: {Tong}")

Các số là bội của 3 và 5:  [0, 3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99, 100, 102, 105, 108, 110, 111, 114, 115, 117, 120, 123, 125, 126, 129, 130, 132, 135, 138, 140, 141, 144, 145, 147, 150, 153, 155, 156, 159, 160, 162, 165, 168, 170, 171, 174, 175, 177, 180, 183, 185, 186, 189, 190, 192, 195, 198, 200, 201, 204, 205, 207, 210, 213, 215, 216, 219, 220, 222, 225, 228, 230, 231, 234, 235, 237, 240, 243, 245, 246, 249, 250, 252, 255, 258, 260, 261, 264, 265, 267, 270, 273, 275, 276, 279, 280, 282, 285, 288, 290, 291, 294, 295, 297, 300, 303, 305, 306, 309, 310, 312, 315, 318, 320, 321, 324, 325, 327, 330, 333, 335, 336, 339, 340, 342, 345, 348, 350, 351, 354, 355, 357, 360, 363, 365, 366, 369, 370, 372, 375, 378, 380, 381, 384, 385, 387, 390, 393, 395, 396, 399, 400, 402, 405, 408, 410, 411, 414, 415, 417, 420, 423, 425, 426, 429, 430, 432, 435, 438,

In [ ]:
# Bài 13
def nhap_mang(ten_mang):
    s = input(f"Nhập các phần tử của {ten_mang} (ví dụ: 1 2 4 5): ")
    return [int(x) for x in s.split()]

a = nhap_mang("mảng a")
b = nhap_mang("mảng b")

def tron_mang(a, b):
    tron = []
    for i in range(max(len(a), len(b))):
        val_a = a[i] if i < len(a) else 0
        val_b = b[i] if i < len(b) else 0
        tron.append(val_a + val_b)
    return tron

ket_qua = tron_mang(a, b)
print("\n")
print(f"Mảng a: {a}")
print(f"Mảng b: {b}")
print(f"Mảng kết quả: {ket_qua}")

In [40]:
# B14
import numpy as mn

m, n = 4, 5
# a.
a = mn.random.randint(1, 50, size=(m, n))
print("Ma trận a:\n", a)

# b, c.
k = int(input("Nhập k: "))
print(f"Dòng {k} : {a[k, :]}")
print(f"Cột {k} : {a[:, k]}")

# d.
print(f"Dòng có tổng lớn nhất: {mn.argmax(a.sum(axis=1))}")

# f.
print("Phần tử dòng chẵn - cột lẻ:")
print(a[0::2, 1::2])

# h.
mask_bien = mn.ones((m, n), dtype=bool)
mask_bien[1:-1, 1:-1] = False
print(f"TBC biên: {a[mask_bien].mean():.2f}")
# i.
if m > 2 and n > 2:
  ktb =  a[1:-1, 1:-1]
  tich_ktb = ktb.prod()
  n_ktb = ktb.size
  tb_tich = tich_ktb ** (1/n_ktb)
  print(f"Ma trận con: \n{ktb}")
  print(f"Tích các phần tử: {tb_tich:.2f}")
else: print("Phần tử quá nhỏ!")

Ma trận a:
 [[43 30 34 11 39]
 [48 28 44 22 30]
 [ 8 12 30 26  6]
 [24 17 39 15 48]]
Nhập k: 1
Dòng 1 : [48 28 44 22 30]
Cột 1 : [30 28 12 17]
Dòng có tổng lớn nhất: 1
Phần tử dòng chẵn - cột lẻ:
[[30 11]
 [12 26]]
TBC biên: 28.00
Ma trận con: 
[[28 44 22]
 [12 30 26]]
Tích các phần tử: 25.16


In [42]:
# Bài 15
from datetime import datetime

# a.
class SinhVien:
    def __init__(self, ma, ten, nam_sinh, dtb):
        self.ma = str(ma)[:10]
        self.ten = str(ten)[:20]
        self.nam_sinh = int(nam_sinh)
        self.dtb = float(dtb)

    def __str__(self):
        return f"MSV: {self.ma} | Tên: {self.ten} | Năm sinh: {self.nam_sinh} | DTB: {self.dtb}"

# b.
n = int(input("Nhập số lượng sinh viên: "))
danh_sach = []
for i in range(n):
     print(f"Nhập SV thứ {i+1}:")
     sv = SinhVien(input(" - Mã SV: "), input(" - Tên: "), input(" - Năm sinh: "), input(" - DTB: "))
     danh_sach.append(sv)

print("--- DANH SÁCH SINH VIÊN ---")
for sv in danh_sach: print(sv)
print("-" * 30)

# c.
len_lop = [s for s in danh_sach if s.dtb >= 5]
print(f"c. Số SV đủ điều kiện lên lớp (DTB >= 5): {len(len_lop)}")

# d.
nam_nay = datetime.now().year
print("d. Các sinh viên đủ 20 tuổi:")
for s in danh_sach:
    if nam_nay - s.nam_sinh >= 20:
        print(f"   + {s.ten} ({nam_nay - s.nam_sinh} tuổi)")

# e.
sv_dh = [s for s in danh_sach if s.ma[2:4] == "DH"]
print(f"e. Số SV học hệ Đại học (có 'DH' trong mã): {len(sv_dh)}")

# f.
sv_ten_lan = [s for s in danh_sach if s.ten.split()[-1].lower() == "lan"]
print(f"f. Số sinh viên có tên 'Lan': {len(sv_ten_lan)}")

# g.
sv_ho_phan = [s for s in danh_sach if s.ten.split()[0].lower() == "phan"]
print(f"g. Số sinh viên có họ 'Phan': {len(sv_ho_phan)}")

Nhập số lượng sinh viên: 2
Nhập SV thứ 1:
 - Mã SV: 01DH007
 - Tên: Trần Thị Lan
 - Năm sinh: 2006
 - DTB: 4.9
Nhập SV thứ 2:
 - Mã SV: 02HV005
 - Tên: Phan Đình Huy
 - Năm sinh: 2006
 - DTB: 8.5
--- DANH SÁCH SINH VIÊN ---
MSV: 01DH007 | Tên: Trần Thị Lan | Năm sinh: 2006 | DTB: 4.9
MSV: 02HV005 | Tên: Phan Đình Huy | Năm sinh: 2006 | DTB: 8.5
------------------------------
c. Số SV đủ điều kiện lên lớp (DTB >= 5): 1
d. Các sinh viên đủ 20 tuổi:
   + Trần Thị Lan (20 tuổi)
   + Phan Đình Huy (20 tuổi)
e. Số SV học hệ Đại học (có 'DH' trong mã): 1
f. Số sinh viên có tên 'Lan': 1
g. Số sinh viên có họ 'Phan': 1
